#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this

sudo cp /etc/hosts /etc/hosts.bak

# Update the hosts file to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts

